name: test_file
on: push

jobs:
  test_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - {ENV1: 1}
          - {ENV1: 2}
    steps:
      - name: echo
        env: ${{ matrix.env }}
        run: ${GITHUB_WORKSPACE}/test.sh